graph TD
  GeorgeWashington["GeorgeWashington :Person"] -->|birthDate 1732-02-22| GWBirthDate["1732-02-22"]
  GeorgeWashington -->|birthPlace| WestmorelandCountyVirginia["WestmorelandCountyVirginia"]
  GeorgeWashington -->|wasPresidentOf| UnitedStates["UnitedStates"]
  GeorgeWashington -->|spouse| MarthaWashington["MarthaWashington"]
